version: '3'
services:

    frontend:
        build: frontend/
        image: frontend
        container_name: frontend
        ports:
            - '3000:3000'
        volumes:
            - ./frontend/src:/app/src
        networks:
            - trascendence

    backend:
        build: backend/
        image: backend
        container_name: backend
        ports:
            - '8081:8081'
        volumes:
            - ./backend/src:/app/src
        depends_on:
            - postgres
        networks:
            - trascendence

    postgres:
        image: postgres:latest
        container_name: postgres
        ports:
            - '5432:5432'
        volumes:
            - /var/folders/postgres:/data/postgres
        env_file:
            - docker.env
        networks:
            - trascendence

networks:
    trascendence:
      name: nw_trascendence

