version: '3'
services:
    frontend:
        build: frontend/
        image: frontend
        container_name: frontend
        ports:
            - '3000:3000'
        volumes:
            - ./frontend/src:/app/src
        networks:
            - trascendence

networks:
    trascendence:

