import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { ButtonIcon, ButtonText, TextInput, TextSeparator } from '@/components/atoms';
import { GoogleIcon, Icon42 } from '../../public/Icons';
import { ModalTemplate } from '@/components/templates';
import styled from 'styled-components';
import { Box } from '@chakra-ui/react';

const AuthOptions = styled.div`
  width: calc(100% - 40px);
  display: grid;
  grid-template-columns: 33% 34% 33%;
  gap: 20px;
  padding: 10px;
`;

const inter = Inter({ subsets: ['latin'] })

const Home: React.FC = () => {
  const handleSubmit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    // Formular submission action here!
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <ModalTemplate>
          <AuthOptions>
            <ButtonIcon>
              <GoogleIcon />
            </ButtonIcon>
            <ButtonIcon>
              <Icon42 />
            </ButtonIcon>
            <ButtonIcon>
              <GoogleIcon />
            </ButtonIcon>
          </AuthOptions>
          <TextSeparator text="Or create an account" />
          <Box>
            <TextInput label="Email" />
            <TextInput label="Password" />
          </Box>
          <ButtonText text="Login" />
        </ModalTemplate>
      </main>
    </>
  );
};

export default Home;
